name: Push image on Azure repository

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKERFILE: ./src/api/Codend.Api/Dockerfile
  TEST_IMAGE_TAG: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/codend/backend-test-build:${{ github.run_id }}
  IMAGE_NAME: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/codend/backend:latest

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_TOKEN }}

      - name: Build and export to Azure Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.TEST_IMAGE_TAG }}
          file: ${{ env.DOCKERFILE }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  unit-tests:
    name: Unit tests in Docker
    needs: [ "build-image" ]
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_TOKEN }}

      - name: Unit Testing in Docker
        run: docker run --rm ${{ env.TEST_IMAGE_TAG }}

  scan-cves:
    name: Run Trivy for all CVEs
    needs: [ "build-image" ]
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy for all CVEs
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.TEST_IMAGE_TAG }}
          exit-code: 0
          format: table
          vuln-type: library
        env:
          TRIVY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.AZURE_REGISTRY_TOKEN }}

  push-image:
    name: Push image on Azure registry
    needs: [ "unit-tests", "scan-cves" ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}
          file: ${{ env.DOCKERFILE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
